/*
INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT highlineNumber,
	highlineName, 
	length, 
	height, 
	stars, 
	whoEstablished, 
	whenEstablished, 
	whoFA, 
	whenFA, 
	climbingBeta, 
	warnings, 
	description, 
	tagging, 
	tensionEnd, 
	gpsLatTensionEnd,
	gpsLonStaticEnd,
	gpsLatTensionEnd,
	gpsLonStaticEnd ,
	tensionEndMainAnchor, 
	tensionEndBackupAnchor, 
	staticEndMainAnchor, 
	staticEndBackupAnchor,
	id FROM GuideAreas
	WHERE guideAreaName = "Beowulf / Deep Water Zawn";
*/


INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 1,
	"Harlequin",
	21,
	20,
	3,
	"Simon Young, Levi Quilliam, Rye Stellard, Drew Abernathy, Sienna DeAngils, Will DeAngils",
	"29/03/2019",
	"Levi Quilliam, Simon Young, Rye Stellard",
	"March 29th 2019",
	NULL,
	NULL,
	"Beautiful beginner line and one of the easiest rigs here. The boulder on the LHS slightly overhangs the water and is a classic big cliff jump, looks smaller than it actually is.",
	"Walk the line around the top of the cliff.",
	"Northern",
	NULL,
	NULL,
 	NULL,
	NULL, 
	"Sling flat flake systems on top of enormous square boulder (3m opened up plus a 3m girth hitched on (double both these up for main and backup)",
	"Find a few additional flakes or cam placements to stop the masterpoint from moving around too much.",
	"Another 10m+ of spansets or rope with lots of rope protection",
	"Small abseil down to large slightly chossy pillar (11m of spansets to wrap it)",
	id FROM GuideAreas
	WHERE guideAreaName = "Beowulf / Deep Water Zawn";


INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 2,
	"Lung Snacks",
	20,
	20,
	3,
	"Chris W, Jack M, Adam E",
	NULL,
	"Max Lee-abbott, Ian Bonnar Bool, Jacob Greiner, Abby Watkins, Chris Wallace, Brendon Plaza, Michael Siriani, Daniel Sinanian, Brad Graham, Max Silver, Preston Bruce, Garrison Rowland, Andrew Criag, Tomas Dabasinskas, Drew Abernathy, Adam Evans, Kyle Beall, Omer, Roberto De Oliveira, Loraine Dawes, Plus more...",
	NULL,
	NULL,
	NULL,
	"Beautiful beginner line however also one of the most challenging to rig and impossible to get level without an a frame (#0.75-0.5 cam and large offset nut for front stabilizing points).",
	NULL,
	NULL,
	NULL,
	NULL,
 	NULL,
	NULL,
	"Easy downclimb on ledges to a good horizontal crack (large nuts, hexes and #1-#0.75 cams)",
	"Small to medium cams and/or rap rope",
	"Sling flat flake systems on top of enormous square boulder",
	"Find a few additional flakes or cam placements to stop the masterpoint from moving around too much.",
	id FROM GuideAreas
	WHERE guideAreaName = "Beowulf / Deep Water Zawn";


INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 3,
	"Ask Toni",
	15,
	15,
	1,
	"Toe-knee Sterai, Rick Kromhust, Dylan Tubaro, Henry Macname",
	"Dec 2019",
	"Toe-knee Sterai, Rick Kromhust", 
	"Dec 2019",
	NULL,
	NULL,
	"A much smaller and accidentally rigged alternative to ‘Old School’.",
	NULL,
	NULL,
	NULL,
	NULL,
 	NULL,
	NULL,
	"Small rap down ‘Beowulf’ to build an anchor from a series of flakes and cams (basically 2m lower than ‘Lung snacks’ anchor)",
	"As for main",
	"Sling medium-ish boulders that are the main way to climb up onto the enormous boulder.",
	"more boulder wrapping",
	id FROM GuideAreas
	WHERE guideAreaName = "Beowulf / Deep Water Zawn";





INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 1,
	"Unknown Name",
	85,
	20,
	2,
	"Stepan Novikov, Jack Vitnell and additional WWW attendees", 
	"01/01/2020",
	"Thomas May, Max Peirce, Danie8l Sinanian, Jacob Grenier, Brendon Plaza, Garrison Rowland, Andrew Craig, Trent Williams, Adam Evans, Roberto De Olivira, Drew Abernathy",
	"01/01/2020",
	NULL,
	NULL,
	"Very pretty and ‘immersive’ line. Not very high so use a static webbing for backup but a great rig nonetheless.",
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	"Medium to large nuts and a large boulder sling far back, 20m of static for main and backup plus lots of rope pro.",
	"As for main",
	"Med to Large cams plus wrap huge slanted boulder, 25m of static to equalise all points plus lots of rope pro.",
	"As for main",
	id FROM GuideAreas
	WHERE guideAreaName = "Lassie’s Wall / Big Zawn";




INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 2,
	"Whipper Tipper",
	35,
	50,
	2,
	"Chen, Axel and Levi",
	"2017",
	"Alex Webber",
	"2017",
	NULL,
	"Although the line was first rigged by wrapping the boulder on the northern side, it is reccomended not to wrap it but rather sling trees behind the boulder and rest the anchor on top of this boulder.",
	"Although a tedious LHS anchor it makes a brilliant line (Hint use dyneema if possible to extend the trees and copious rope protection on the pillar). One of the highest of any here and also the scene of a few rope swings (some without traditional harnesses).",
	NULL,
	"Southern",
	NULL,
	NULL,
	NULL,
	NULL,
	"2x U bolts hidden at foot level.",
	"There are numerous natural options the best being a large ‘fridge size’ boulder directly behind the bolts.",
	"Use a series of trees (4 is best) and extend them roughly 10m-15m forward using the ‘tipper dipper’ boulder as an A-Frame. Please do NOT anchor only off the boulder.",
	"As for main",
	id FROM GuideAreas
	WHERE guideAreaName = "Lassie’s Wall / Big Zawn";

INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 3,
	"Close Shave",
	30,
	45,
	1,
	"Chen, Axel and Levi",
	"2017",
	"Alex Webber",
	"2017",
	NULL,
	NULL,
	"The snapped anchor tree is a testament to how fragile the timber in the area is (if you look around it's not the only one that's fallen over recently).",
	NULL,
	"Northern",
	NULL,
	NULL,
	NULL,
	NULL,
	"Equalise a few trees far back from the edge and use the snapped stump as an A-Frame. This snapped tree was used for the first few rigs as the anchor, before it broke!",
	"As for main (use rope pro for the backup webbing near the anchor)",
	"3 U bolts in the back of the tallish boulder (at eye level)",
	"As for main",
	id FROM GuideAreas
	WHERE guideAreaName = "Lassie’s Wall / Big Zawn";

INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 1,
	"Starburst",
	30,
	20,
	2,
	"Chen and Levi",
	"2018",
	NULL,
	NULL,
	"Best if your drop a line down the rock face to get to the middle island. Then for getting out TRS back up the line you dropped down.",
	NULL,
	"Beaut little line from White Stack cliff to the island of rock 30m away. The access track down to the mainland anchor skirts a steep and exposed section of cliff, falling off or breaking a hand hold is a very real possibility, not the ideal area to bring someone uncomfortable with cliffs, consider putting in a static rope safety line, 20-30m static should do it. Also an additional 20m of rope is required to access the base of cliffs in order to scramble up the island. ",
	NULL,
	"Southern",
	NULL,
	NULL,
	NULL,
	NULL, 
	"2x U bolts with an inconvenient 3-5m no fall zone in front of them",
	"As for main",
	"2x U bolts. Use a BD #5 cam to pull the masterpoint down to avoid rubbing (bolts are close together and about 6m back from the edge)",
	"As for main",
	id FROM GuideAreas
	WHERE guideAreaName = "White Stack Area";

INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 2, 
	"Bendy Wendy",
	55,
	40,
	2,
	"Levi, Simon, Drew",
	"01/02/2019",
	"Levi and Drew",
	"01/02/2019",
	"Best if your drop a line down the rock face to get to the middle island. Then for getting out TRS back up the line you dropped down.",
	"The northern end anchor is questionable, make sure to give it a good close inspection.",
	"A great addition to the area, all natural and stunningly obvious.",
	"Rap down the cliff with one end of the line, walk over to the other side, attach it to a rope and have the team pull it up.",
	"Southern",
	NULL,
	NULL,
	NULL,
	NULL,
	"Wrap large pillar at very top of White Stack area (8-12m of spanset?)",
	"As for main",
	"Wrap boulders atop the ridgeline that separates Lassies from white stack and use a dodgy but obvious tree to redirect the anchor 6-8m down and level.",
	"As for main.",
	id FROM GuideAreas
	WHERE guideAreaName = "White Stack Area";
	
/* Cataract Gorge */
	
INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd REAL, gpsLonStaticEnd REAL, gpsLatTensionEnd REAL, gpsLonStaticEnd REAL, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 1,
	"BOB", 
	56, 
	16, 
	0, 
	"Daniel Hoi Shun Ng", 
	"01/01/2015", 
	"Daniel Hoi Shun Ng",
	"01/02/2015", 
	NULL, 
	"As the line crosses about 1m overhead of one of the main gorge walking tracks on the east side it is advisable to ensure public safety is carefully considered whilst rigging and walking.", 
	"Easy rigging on this fully bolted highline with ease of line crossing by using the suspension bridge right next to this highline. Daniel brought sport climbing to Cataract Gorge in the 1980’s and has been a contributor to the climbing scene in the gorge for a number of years since the first bolted sport route. He opened the eyes to the potential for fun lines up previously unprotected aretes and blank faces.Now Daniel has also brought the first established highline to the gorge in 2015. This line is remarkably easy to rig and will become a highline that can be rigged on the regular by any slackers passing through.", 
	NULL, 
	NULL, 
	NULL,
	NULL,
	NULL,
	NULL,
	"4 x 8mm thru expansion bolts", 
	"1 x 8mm thru expansion bolt & tree", 
	"3 x 8mm thru expansion bolts", 
	"2 x 8mm thru expansion bolts",
	id FROM GuideAreas
	WHERE guideAreaName = "Cataract Gorge";
	
INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 2,
	"Danny", 
	80, 
	50, 
	0, 
	"James Short, Joseph Huard, Gui Lopes, Daniel Hoi Shung Ng", 
	"01/01/2015", 
	"Joseph Huard", 
	"01/02/2015", 
	NULL, 
	"Edge protection is required for these blocks with a few sharp contours to protect. Both sides are reasonably dangerous to access and set up rigging. Also beware of loose rocks that could dislodge and trundle down the hill towards walkers and other user groups. Ensure care is taken to retain access to the gorge.", 
	"Having both highlines rigged at once is magical. A line originally spotted and visioned by Daniel Hoi Shung Ng, he had mentioned it to the SHF team who subsequently came and located/ established the line. Daniel provided his Spider Silk webbing to rig the highline and Joseph sent it onsight. Daniel Hoi Shung Ng passed away in December of 2015 in a tragic accident and will be remembered greatly for his efforts in Hong Kong/ China and his contributions to establishing some of the most classic sport climbs in Cataract gorge. He will be forever remembered by this line above his good friend Bob’.", 
	NULL, 
	NULL, 
	NULL,
	NULL,
	NULL,
	NULL ,
	"9m girth around obvious blade/ block level with the lookout railing (note* there are two blocks however one is obviously more secure upon inspection)", 
	"As for main", 
	"10m girth around obvious block high up on the gorge wall, difficult to position the slings", 
	"As for main",
	id FROM GuideAreas
	WHERE guideAreaName = "Cataract Gorge";
	
-- Ben Lomond

INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 1,
	"Line Name", 
	80, 
	80, 
	3, 
	"Stepan Novikov, Divya Gordon, Charlie Horton, Brendon Plaza, Chris Wallace, Art Ho-Baley", 
	NULL, 
	"Stepan Novikov", 
	"01/02/2019", 
	NULL, 
	NULL, 
	"Beautiful Line, slightly difficult to get onto on the RHS (no ledges) and requiring some exposed scrambling and rock hops to get to the LHS anchor. Clean falls the entire way and great direct height in the middle.", 
	NULL, 
	NULL, 
	NULL,
	NULL,
	NULL,
	NULL ,
	"A series of boulder wraps and trad gear (medium cams and nuts) using a prominent flat topped pillar as an A-frame (roughly 1.5m x 1.5m on top)", 
	"As for main", 
	"A series of wraps and Trad gear using another flat topped pillar as an A-frame.", 
	"As for main",
	id FROM GuideAreas
	WHERE guideAreaName = "Jacob's Ladder";
	
INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 1,
	"Line Name", 
	45, 
	NULL, 
	0, 
	"Jerry M, Faith Dickey, Preston Allen-Bruce, Max Silver, + more", 
	"01/01/2017", 
	"Probably all involved", 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL,
	NULL,
	NULL,
	NULL ,
	NULL, 
	NULL, 
	NULL, 
	NULL,
	id FROM GuideAreas
	WHERE guideAreaName = "Flew's Flutes";
	
INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 2,
	"Line Name", 
	35, 
	NULL, 
	0, 
	"Preston Allen-Bruce, Max Silver, Andrew", 
	"01/01/2018", 
	"Probably all involved", 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	NULL,
	NULL,
	NULL,
	NULL ,
	NULL, 
	NULL, 
	NULL, 
	NULL,
	id FROM GuideAreas
	WHERE guideAreaName = "Flew's Flutes";
	
-- Freycinet, Nicholas' Needle
	
INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 1,
	"Line Name", 
	130, 
	60, 
	0, 
	"Brendon Plaza, Ian Bool, Jacob Grenier, Max Peirce, Eric Peirce, Stepan Novikov, Divya Gordon, Chris Wallace", 
	NULL, 
	"Max Peirce", 
	NULL, 
	"The pillar can be found on Thesarvo. Bring a standard rack of cams from micro to #2 along with a small selection of nuts (micro to large) and roughly 10 alpine draws. Expect the placements to be average and the climbing to be around grade 17 on average rock quality with high ledge fall potential. To find the start scramble up into the large east notch and abseil 10-15m down the other side to a hanging belay on the spiky shrubs. P1 - climb the mossy wall up the easiest weakness, trending left and mounting a few tricky mantles. Follow the line of easiest weakness up the jam crack (passing old piton) and into difficult vegetated mantle. Build belay here. P2 - scramble up diagonal slope to the left (15m). P3 - Up the easy but barely secured boulders, belay from a large boulder and single bolt on the far side of the top. A 60m rope is enough to rap back down into the notch with (30mish)", 
	NULL, 
	"Stunning line and the most obvious king line in the region.", 
	NULL, 
	NULL, 
	NULL,
	NULL,
	NULL,
	NULL ,
	"Equalise a couple medium sized eucalyptus trees roughly 12m back from the edge and build a masterpoint on top of the prominent dolerite boulder/spire.", 
	"As for main (super long dyneema whoopies and rope pro are handy)", 
	"Equalise a number of small shrubs, boulders and the single bolt and medium boulder. Bring rope pro", 
	"As for main",
	id FROM GuideAreas
	WHERE guideAreaName = "TNicholas' Needle";

-- NORTH WEST TASMANIA
-- Cradle Mountain - Lake St Clair National Park (Mt Geryon and The Acropolis)

INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 1,
	"The Book of Laughter and Forgetting", 
	43, 
	100, 
	3, 
	"Stepan Novikov, Alex Bog, Kamil Sustak and Simmon Madden", 
	"01/01/2016", 
	"Stepan Novikov", 
	NULL, 
	NULL, 
	NULL, 
	"The first line on Mt Geryon and a proper achievement for the time. No beta, No sussing missions, onsight alpine highlining. 500m+ exposure.", 
	NULL, 
	NULL, 
	NULL,
	NULL,
	NULL,
	NULL ,
	"North - Huge block. Roughly 7-8m to sling (dyneema works). Bring lots of rope pro!", 
	"As for main", 
	"South - Foresight. 9m of material to wrap the summit (double it for a backup) + rope pro.", 
	"As for main",
	id FROM GuideAreas
	WHERE guideAreaName = "Mt Geryon and The Acropolis";
	
INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 2,
	"Savour The Flavour", 
	20, 
	60, 
	4, 
	"Chris Wallace, Max Silver, James Short and additional support from 9 others", 
	NULL, 
	"Chris Wallace, Max Silver, James Short, Brendon Plaza, Ian Bool, Max Lee-Abbott, Brad Graham, Toeknee Sterai, Thom May", 
	NULL, 
	"The easiest way to rig is probably to follow option 1 in the access section and have a team climb the foresight. If the group are strong climbers, doing the geryon traverse is probably cleaner.", 
	NULL, 
	"Maybe the best of the bunch and also the most challenging to rig. As far as short highlines go, this is probably the best in Australia, the 400m exposure is just all time.", 
	"A 20m tagline throw is required to link this (difficult in the wind) alternatively if the access to the south summit is via climbing, trail a tagline.", 
	NULL, 
	NULL,
	NULL,
	NULL,
	NULL,
	"North - Foresight. Wrap the summit blocks using a bowline hitch to enable the line to be level. 9m of rope required (double it for backup) and a #2-3 Cam to make sure the wrap doesn’t slip off", 
	"As for main", 
	"South - From the south geryon tower, Rap / Scramble (very exposed grade 12) down to level with the foresight (20m of rope required). Anchor off two ideal horns of rock on the east side of the mountain. 8m of material to girth hitch both and tie a BFK.", 
	"As for main",
	id FROM GuideAreas
	WHERE guideAreaName = "Mt Geryon and The Acropolis";

INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 3,
	"Keep Calm and Geryon", 
	63, 
	120, 
	4, 
	"Max Silver, James Short, Garrison Rowland, Preston Bruce and Andrew Craig", 
	"01/01/2018", 
	"Garrison Rowland, Andrew Craig", 
	NULL, 
	NULL, 
	NULL, 
	"The king line of the area and historically a coveted prize. Originally the goal of the 2016 russian expedition however when it was discovered to be too long “TBLF” was rigged instead. The following year an American team attempted it and on finding the climbing traverse too sketchy also rigged “TBLF”. One year later they returned again, this time with James Short and re-attempted the rig by avoiding the traverse. The team split into two and ascended either summit of geryon (the prefered method) and successfully pulled it off.", 
	NULL, 
	NULL, 
	NULL,
	NULL,
	NULL,
	NULL,
	"North - Wrap the ‘tunnel of love’ using about 15m of static or dyneema. More points can be used for stability (these are smaller boulders all around the area, 4m of material per boulder should be enough to incorporate them). Bring lots of rope pro (at least 10 pieces minimum)", 
	"As for main", 
	"South - A few different options here. Either scorpion the huge horizontal block (a little sketch) or sling a ‘locked in’ block that is slightly higher but requires some horizontal stabilization. This second option uses 6m for main (6m more for backup) and about 15-20m of cord for stabilizers. Once again, Lots of rope pro required.", 
	"As for main",
	id FROM GuideAreas
	WHERE guideAreaName = "Mt Geryon and The Acropolis";

INSERT INTO Highlines(highlineNumber, highlineName, length, height, stars, whoEstablished, whenEstablished, whoFA, whenFA, climbingBeta, warnings, description, tagging, tensionEnd, gpsLatTensionEnd, gpsLonStaticEnd, gpsLatTensionEnd, gpsLonStaticEnd, tensionEndMainAnchor, tensionEndBackupAnchor, staticEndMainAnchor,  staticEndBackupAnchor, parentID)
	SELECT 4,
	"Sloopy Dumper Number Something", 
	40, 
	200, 
	0, 
	"Max Silver, Garrison Rowland, Preston Bruce and Andrew Craig", 
	"01/01/2017", 
	NULL, 
	NULL, 
	NULL, 
	NULL, 
	"The ‘hidden’ V groove a few hundred meters away from camp up on the ridge.", 
	NULL, 
	NULL, 
	NULL,
	NULL,
	NULL,
	NULL,
	NULL, 
	NULL, 
	NULL, 
	NULL,
	id FROM GuideAreas
	WHERE guideAreaName = "Mt Geryon and The Acropolis";
